### ISSUE TITLE
Set up project structure

### ISSUE THREAD

**Issue by ZeroKnight** [mtsac-tech-health/HP-Softpaq-Orchestrator#10]
Follow modern Python packaging/project structure approaches and set up at least a basic initial structure to facilitate working with the project, e.g. editable pip install, dev tools (linting, type checking, testing), tox, etc.

# To Do

- [x] pyproject.toml
  - [x] [Core metadata](https://packaging.python.org/en/latest/specifications/core-metadata)
  - [x] (Optional) Dependencies
  - [x] Tool configuration (Black, isort, mypy etc.)
- [x] Package is buildable by `pip`/`setuptools`
- [x] tox.ini
  - [x] Root testenv settings
  - [x] Linter testenvs
  - [x] Build testenv
  - [x] Leverage [tox-gh plugin](https://github.com/tox-dev/tox-gh)
  - [x] Add `black --check` and `isort --check` to the lints to ensure style
  - [x] `tox devenv` target
- [x] Add new tox-based Actions workflow
- [x] Add license
- [x] Ensure `src` layout is correct with everything

**Comment by ZeroKnight** [comment]
Hey @rluzuriaga, while I'm working on all this meta-project stuff, I figured that now would be as good of a time as any to bikeshed about the package name a bit. In no particular order, some things to consider:

- Consistency in the casing of "Softpaq" vs "SoftPaq"
  - HP seems to prefer "SoftPaq" in prose but will use "Softpaq" in things like PowerShell cmdlets (likely due to PS naming convention)
  - Our repository name uses a lower-case "p" but the package name uses a capital "P"
  - Going forward, we should also try to be consistent with whichever variant we settle on
- PEP 8 convention _prefers_ lowercase module/package names whereas ours is currently pascal-cased
  - While I tend to agree with PEP 8 on this, I'm not fanatical about it and think pascal-case is a fine alternative. That being said, I would prefer "Softpaq" over "SoftPaq"
  - On that note, I *don't* think that `softpaqorchestrator` would be better, for the record
- Consider a secondary, shortened name package name
  - `SoftPaqOrchestrator` feels a bit clumsy to type (I would prefer at least `SoftpaqOrchestrator` as above), so perhaps we could use a more friendly name for the package, while keeping the verbose name for the repository/readme
  - We could have a bit of fun with it; something that came to mind was `sporc`, which is short, easy to type, and kind of funny. Maybe even `sporca`, like a killer-whale spork 😆
  - Definitely open to opinions here

In general, I kind of prefer "Softpaq" all around since it's easier to type and I think subjectively that it looks better.

Let me know your thoughts when you have a moment! I'd like to know your opinions/preferences.

**Comment by rluzuriaga** [comment]
Hey @ZeroKnight sorry it took me forever to reply.

- I think we should be consistent with naming it "Softpaq"
- Even though PEP 8 convention is all lowercase, I think that `softpaqorchestrator` just looks worse than `SoftpaqOrchestrator` so I would prefer the latter.
- I'm not planning on having this project up on PyPi so I think for now leaving it as `SoftpaqOrchestrator` should be fine.

**Comment by ZeroKnight** [comment]
No worries! Thanks for adding your thoughts. I think I'll do these changes in a separate PR since there's already enough going on in the other one.
